import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Klasse als Bespiel zum Schreiben von Daten in die DB. create table wetter (
 * id int generated by default as identity (start with 1), 
 * stadt varchar(255),
 * temp int );
 * 
 * @param args
 */

public class SQLWriter {

	public static void main(String[] args) {

		try {
			Connection con = HSQLDBConnector.createConnection();
			
			// Schritt !: Statement Objekt
			Statement stmt = con.createStatement();
			
			
			// Schritt 2: SQL Befehl definieren
			String sql = "INSERT INTO wetter (stadt, temp) VALUES ('Ravensburg', 10)";
			System.out.println(sql);
			
			// Schritt §: Ausführen des befehls
			stmt.executeUpdate(sql);

			// Schließen
			stmt.close();
			con.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}
